# Generated by Django 4.0.6 on 2022-07-11 15:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA_CADASTRO', models.DateTimeField(default=datetime.datetime(2022, 7, 11, 12, 27, 16, 481750))),
                ('NOME_EMPRESA', models.CharField(max_length=200)),
                ('CPF_CNPJ', models.CharField(max_length=200)),
                ('CEP', models.CharField(max_length=10)),
                ('ENDERECO', models.CharField(max_length=200)),
                ('BAIRRO', models.CharField(max_length=200)),
                ('NUMERO', models.CharField(max_length=6)),
                ('COMPLEMENTO', models.CharField(max_length=100)),
                ('CIDADE', models.CharField(max_length=200)),
                ('ESTADO', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO'), ('DF', 'DF')], max_length=2)),
                ('EMAIL_RESPONSAVEL', models.EmailField(max_length=254)),
                ('EMAIL_FINANCEIRO', models.EmailField(max_length=254)),
                ('OBS', models.CharField(blank=True, max_length=500)),
                ('RESPONSAVEL', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME_USUARIO', models.CharField(max_length=200)),
                ('DATA_CADASTRO', models.DateTimeField(default=datetime.datetime(2022, 7, 11, 12, 27, 16, 482659))),
                ('ID_EMPRESA', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autenticacao.empresa')),
                ('USUARIO', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
