# Generated by Django 4.0.6 on 2022-07-11 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='USUARIO',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='DATA_CADASTRO',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 12, 28, 15, 973765)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='DATA_CADASTRO',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 12, 28, 15, 974733)),
        ),
    ]
