# Generated by Django 4.0.6 on 2022-07-11 15:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autenticacao', '0002_remove_usuario_usuario_alter_empresa_data_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='USUARIO',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='DATA_CADASTRO',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 12, 28, 46, 351653)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='DATA_CADASTRO',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 11, 12, 28, 46, 352715)),
        ),
    ]
